---
- hosts: www

  vars:
    - root_dir: ..


  pre_tasks:
    - debug: msg="Pre tasks section"

  roles:
     - {
         role: "sa-nginx"
       }
     - {
         role: "sa-cockpit"
       }


  tasks:

    - debug: msg="Tasks section"

    - template: src="{{root_dir}}/templates/nginx.conf.j2" dest="/etc/nginx/sites-enabled/cockpit"
      become: yes

    - service: name="nginx" state="restarted"
      become: yes
